### ISSUE TITLE
[5] Wireframe of makeups store category

### ISSUE THREAD

**Issue by bloodline09** [janMaynard/Team-5#9]

**Comment by CodieTyler21** [comment]
![MAKEUP](https://user-images.githubusercontent.com/94656103/146570365-e8ff6a77-dc32-42fa-ae55-f4dea29b38a9.jpeg)
We did use the Lucidchart.com to make wireframe for makeups store category or more like a beauty store category. With the design and it's simplicity this is more satisfactory than the others also given that there is a lot of beauty store now all throughout the country, we give this wireframe a unique 5 points.
